spring.application.name=photo-app-configuration-server
spring.profiles.active=git
server.port=8888

# Encryption Security Configuration
encrypt.keyStore.location=classpath:/keystore.p12
encrypt.keyStore.password=${KEYSTORE_PASSWORD}
encrypt.keyStore.alias=mykey

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

management.endpoints.web.exposure.include=busrefresh,health,info
