spring.application.name=photo-app-albums-service
spring.profiles.active=dev
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.username=${CONFIG_SERVER_ADMIN_USER}
spring.cloud.config.password=${CONFIG_SERVER_ADMIN_PASSWORD}
