spring.application.name=photo-app-configuration-server
server.port=8888

# native or git
spring.profiles.active=native

# Remote Configuration
spring.cloud.config.server.git.uri=https://github.com/ossantvng-dev/photo-app-configuration-repo
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_TOKEN}
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=config-repo
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true

# File System Backend Configuration
spring.cloud.config.server.native.search-locations=${CONFIG_REPO_PATH}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.endpoints.web.exposure.include=busrefresh,health,info
