<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0" 
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.ossantvng.photoapp</groupId>
	<artifactId>api-parent</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>api-parent</name>
	<description>API Parent</description>
	<packaging>pom</packaging>
	
	<modules>
		<module>commons-lib</module>
		<module>security-lib</module>
		<module>entity-model-lib</module>
		<module>feign-lib</module>
		<module>users-service</module>
		<module>accounts-service</module>
		<module>photos-service</module>
		<module>albums-service</module>
		<module>api-gateway</module>
		<module>config-server</module>
		<module>discovery-service</module>
	</modules>

</project>
