spring.datasource.url=jdbc:mysql://localhost:3306/photo_app?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=photo_app_user
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration

logging.level.org.hibernate.type.descriptor.sql=trace
