spring.application.name=photo-app-albums-service
spring.profiles.active=local
server.port=8083
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}