spring.application.name=photo-app-users-service
spring.profiles.active=dev
spring.config.import=optional:configserver:http://localhost:8888
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
spring.cloud.config.username=${CONFIG_SERVER_ADMIN_USER}
spring.cloud.config.password=${CONFIG_SERVER_ADMIN_PASSWORD}
