server.port=8080
spring.application.name=photo-app-api-gateway

spring.main.web-application-type=reactive

# =========================
# EUREKA
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.registry-fetch-interval-seconds=5
eureka.instance.prefer-ip-address=true

# =========================
# GATEWAY
# =========================
spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.server.webflux.routes[0].id=users-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PHOTO-APP-USERS-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[1].id=albums-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://PHOTO-APP-ALBUMS-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/albums/**

spring.cloud.gateway.server.webflux.routes[2].id=photos-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PHOTO-APP-PHOTOS-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/photos/**

spring.cloud.gateway.server.webflux.routes[3].id=accounts-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://PHOTO-APP-ACCOUNTS-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/accounts/**

# =========================
# ACTUATOR
# =========================
management.endpoints.web.exposure.include=*

# =========================
# LOGGING
# =========================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=TRACE